DROP TABLE pearlwhite85.inv_data_bk;
CREATE TABLE pearlwhite85.inv_data_bk
  (
    prod_cd       CHAR(21) NOT NULL PRIMARY KEY,
    whs_num       CHAR(8) DEFAULT ' ',
    in_stock      NUMERIC(21,6)  DEFAULT 0,
    lastrcv_qty   NUMERIC(21,6) DEFAULT 0,
    lastrcv_dt    NUMERIC(8,0) DEFAULT 0,
    price_base    NUMERIC(21,6) DEFAULT 0,
    frt_cus       NUMERIC(21,6) DEFAULT 0,
    prod_duty     NUMERIC(21,6) DEFAULT 0,
    handl_fee     NUMERIC(21,6) DEFAULT 0,
    misc_fee      NUMERIC(21,6) DEFAULT 0,
    avg_cost      NUMERIC(21,6) DEFAULT 0,
    lt_sl_dt      NUMERIC(8,0) DEFAULT 0,
    vendor        CHAR(10) ,
    lst_order     NUMERIC(21,6) DEFAULT 0,
    ord_dt        NUMERIC(8,0) DEFAULT 0,
    stk_ind       CHAR(1),
    back_qty      NUMERIC(21,6) DEFAULT 0,
    order_qty     NUMERIC(21,6) DEFAULT 0,
    on_order_qty  NUMERIC(21,6) DEFAULT 0,
    wip_qty       NUMERIC(21,6) DEFAULT 0,
    rma_qty       NUMERIC(21,6) DEFAULT 0,
    water_qty     NUMERIC(21,6) DEFAULT 0,
    ordersize     NUMERIC(21,6) DEFAULT 0,
    minstock      NUMERIC(21,6) DEFAULT 0,
    inv_loc       CHAR(20),
    unit_color    CHAR(11),
    class_cd      CHAR(20),
    descrip       CHAR(61),
    def_unit      CHAR(2),
    updt_dt       NUMERIC(8,0) DEFAULT 0,
    phyc_dt       NUMERIC(21,6) DEFAULT 0,
    image_nm      CHAR(80),
    oem_cd        CHAR(20),
    alt_cd        CHAR(20),
    updt_by       CHAR(8),
    currency_cost NUMERIC(21,6) DEFAULT 0,
    cost_factor   NUMERIC(21,6) DEFAULT 0,
    status 	    CHAR(1) DEFAULT 'N' NOT NULL;
  );