drop table inv_data;
create table inv_data
	(prod_cd char(21) not null unique,
	whs_num char(8) not null unique,
	in_stock numeric(21,6) not null,
	lastrcv_qty numeric(21,6),
	LASTRCV_DT numeric(8,0),
	price_base numeric(21,6),
	FRT_CUS numeric(21,6),
	PROD_DUTY numeric(21,6),
	HANDL_FEE numeric(21,6),
	MISC_FEE numeric(21,6),
	AVG_COST numeric(21,6),
	LT_SL_DT numeric(8,0),
	VENDOR char(10),
	LST_ORDER numeric(21,6),
	ORD_DT numeric(8,0),
	STK_IND char(1),
	BACK_QTY numeric(21,6),
	ORDER_QTY numeric(21,6),
	ON_ORDER_QTY numeric(21,6),
	WIP_QTY numeric(21,6),
	RMA_QTY numeric(21,6),
	WATER_QTY numeric(21,6),
	ORDERSIZE numeric(21,6),
	MINSTOCK numeric(21,6),
	INV_LOC char(20),
	DEF_UNIT char(2),
	UPDT_DT numeric(8,0),
	PHYC_DT numeric(21,6),
	IMAGE_NM char(80),
	OEM_CD char(20),
	ALT_CD char(20),
	UPDT_BY char(8),
	CURRENCY_COST numeric(21,6),
	COST_FACTOR numeric(21,6));
commit;