drop table inv_data;
create table inv_data
	(prod_cd char(21) not null unique,
	whs_num char(8) not null unique,
	in_stock numeric(21,6) not null,
	lastrcv_qty numeric(21,6),
	lastrcv_dt numeric(8,0),
	price_base numeric(21,6),
	frt_cus numeric(21,6),
	prod_duty numeric(21,6),
	handl_fee numeric(21,6),
	misc_fee numeric(21,6),
	avg_cost numeric(21,6),
	lt_sl_dt numeric(8,0),
	vendor char(10),
	lst_order numeric(21,6),
	ord_dt numeric(8,0),
	stk_ind char(1),
	back_qty numeric(21,6),
	order_qty numeric(21,6),
	on_order_qty numeric(21,6),
	wip_qty numeric(21,6),
	rma_qty numeric(21,6),
	water_qty numeric(21,6),
	ordersize numeric(21,6),
	minstock numeric(21,6),
	inv_loc char(20),
	unit_color 	 char(11),
	class_cd char(20),
	descrip char(61),
	def_unit char(2),
	updt_dt numeric(8,0),
	phyc_dt numeric(21,6),
	image_nm char(80),
	oem_cd char(20),
	alt_cd char(20),
	updt_by char(8),
	currency_cost numeric(21,6),
	cost_factor numeric(21,6));
commit;